import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  // --------------------------------------------------------------------------------
  // 📌  Main app exit component
  // --------------------------------------------------------------------------------

  return (
    <div className="app-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>app</div>
    </div>
  );
};

export default Home;
